# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 4f0eb78e3f88a591bd714d9d98570db18692037e682620d8deb430a0ca2797e4a5b8b9602f3e72f582cfb645a948ed88ca4311f57f5710b337c09f4338855977

test:
  secret_key_base: 07de5c82d8af4fcaac2aa0401d6e1585a8e56d0b79ee027b37dd56e97a4928cf83f5bed4b1d1c0db3d5dc324ce96fb52281878beaa0074ec9287a8156c2a6426

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
